studySpec:
  metrics:
    - metricId: kschool_accuracy
      goal: MAXIMIZE
  parameters:
    - parameterId: epochs
      integerValueSpec:
        minValue: 10
        maxValue: 50
    - parameterId: batch-size
      discreteValueSpec:
        values:
          - 128
          - 256
          - 512
          - 1024
          - 2048
          - 4096
trialJobSpec:
  #serviceAccount: SOME_SERVICE_ACCOUNT
  #tensorboard: SOME_TENSORBOARD
  baseOutputDirectory:
    outputUriPrefix: gs://ferrous-linker-339609/ht-training-output/
  workerPoolSpecs:
    machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: europe-docker.pkg.dev/vertex-ai/training/tf-cpu.2-7:latest
      packageUris: gs://ferrous-linker-339609/dist/my_first_ml_model-0.2+1.gb68252e.tar.gz
      pythonModule: trainer.task
      args:
        - --data-location=gs://ferrous-linker-339609/output/
        - --tft-location=gs://ferrous-linker-339609/output/transform_fn/

